# Generated by Django 4.1.4 on 2022-12-21 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_reading_options_book_teas_alter_reading_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='rating',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='tea',
            name='rating',
            field=models.IntegerField(max_length=10),
        ),
    ]
